language: ruby
sudo: false
rvm:
- 2.2.3
cache:
  bundler: true
env:
- DB=pgsql
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database totem_docs_test' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rake db:test:prepare
- bundle exec rake
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ph3wqXvh91u7Fv1r9SCKn3k/Be1d8LlnmbNUkD6tcGRiBEXxcEJhADr04xbVG6xUDm7fM1/btke+3a448zDm3mOtqqJLqa5mV9rdeqYrzhpiBz40XYzO+vhz5KsYx5bh7LHV6Y1JSmPNR0P+TMpFsOhbSQnFeYvxeHSz6tlU3VaFDgNZBU3ayhBw4o70ksjZSKoWOK9eHJTKs1AFvFKYlLYG88Ah4UyjXF7Z+VRfmSVyjE19URg0P3V9jc2H8OqMKGVkEAFUMzSBd/Dj9KOaIBglK+/aC6QBkICiFkSMIo5t0Qs2LepFgqCIJB7RLYZKrz90pJwaavl1Ooaa6zd1TK5W2zuvClY9n2hnkv/6wxnZB29pv9Eb+/2Vd3Rca/zv2XbY1uWQVf82bs3IPx3lXdzh4K7ejAzNdE0SyutUw0cYC4Gj8O0/XZ/uIhZ0zTelqiGuDRhfSEwkyUwTorvGrsqMQAUBwLaWkEPfMLKXpngszGUEvXGA7ncr3NKMOWNooodlJ44J5CsTUzXBbJ6Dq5x263HPRS9ad1y4mHnF+0YFXJ2JVhIp6gBryDRslKihyc5Ngt52xUfBdEtHSInYvaJX4Rps5wcOSxlmPSYyV0DSqUWf/lLzby6JTG1wbFGPTpLatWoxUpcj1K34UJ4zPO8+ENRelp0iPvDcCdyPJ4Y=
  on: master
  run:
  - rails db:migrate
  - rails totem:lodestar:generate
  - rails totem:lodestar:api[false]
  # - npm install
  # - rails totem:lodestar:api
