text:
  title:     Totem docs
  sub-title: Add your subtitle in config/settings.yml!
modules:
  versions:
    index_redirect: true
  side_bar:
    collapse:
      enabled: true
  table_of_contents:
    smooth_scroll:
      enabled: true
    highlight: 
      enabled: false

