text:
  title: Totem docs
  logo:  false
modules:
  layout:
    full_width:
      enabled: true
      default: true

  versions:
    index_redirect: true

  side_bar:
    collapse:
      enabled:        true
      expanded_icon:  'fa fa-minus right'
      collapsed_icon: 'fa fa-plus right'

  table_of_contents:
    smooth_scroll:
      enabled: true
      speed:   300 # Milliseconds
    highlight: 
      enabled: true

  api:      
    repositories:
      - name: ethinkspace-client
        url: 'https://github.com/sixthedge/ethinkspace-client'
        branch: feature/pe-builder
        options:
          out:     "-o ../../api/ethinkspace-client"
          glob:    "./**/*.coffee README.md"
          project: "-p ethinkspace-client"
          url:     "--repository-url 'https://github.com/sixthedge/ethinkspace-client'"

      - name: ethinkspace-api
        url: 'https://github.com/sixthedge/ethinkspace-api'
        branch: feature/pe-builder
        options:
          out: "-o ../../api/ethinkspace-api"
          glob: "./**/**/*.rb README.md"
          project: "-p ethinkspace-api"
          url:     "--repository-url 'https://github.com/sixthedge/ethinkspace-api'"