text:
  title:     Totem docs
  sub-title: Building software one stack at a time
modules:
  layout:
    full_width:
      enabled: true
      default: true

  versions:
    index_redirect: true

  side_bar:
    collapse:
      enabled:        true
      expanded_icon:  'fa fa-minus right'
      collapsed_icon: 'fa fa-plus right'

  table_of_contents:
    smooth_scroll:
      enabled: true
      speed:   300 # Milliseconds
    highlight: 
      enabled: true

 