text:
  title: Totem docs
  logo:  false
modules:
  layout:
    full_width:
      enabled: true
      default: true

  versions:
    index_redirect: true

  side_bar:
    collapse:
      enabled:        true
      expanded_icon:  'fa fa-minus right'
      collapsed_icon: 'fa fa-plus right'

  table_of_contents:
    smooth_scroll:
      enabled: true
      speed:   300 # Milliseconds
    highlight: 
      enabled: true

  api:      
    repositories:
      - name: ethinkspace-client
        url: 'https://github.com/sixthedge/ethinkspace-client'
        branch: feature/pe-builder-comments
        options:
          out:     "-o ../../api/ethinkspace-client"
          glob:    "./**/*.coffee README.md"
          project: "-p ethinkspace-client"
          url:     "--repository-url 'https://github.com/sixthedge/ethinkspace-client'"

      - name: ethinkspace-api
        url: 'https://github.com/sixthedge/ethinkspace-api'
        branch: master
        options:
          out: "-o ../../api/ethinkspace-api"
          glob: "./**/**/*.rb README.md"
          project: "-p ethinkspace-api"
          url:     "--repository-url 'https://github.com/sixthedge/ethinkspace-api'"

      - name: etotem-client
        url: 'https://github.com/sixthedge/etotem-client'
        branch: development
        options:
          out:     "-o ../../api/etotem-client"
          glob:    "./**/*.coffee README.md"
          project: "-p etotem-client"
          url:     "--repository-url 'https://github.com/sixthedge/etotem-client'"

      - name: etotem-api
        url: 'https://github.com/sixthedge/etotem-api'
        branch: master
        options:
          out: "-o ../../api/etotem-api"
          glob: "./**/**/*.rb README.md"
          project: "-p etotem-api"
          url:     "--repository-url 'https://github.com/sixthedge/etotem-api'"

      # - name: totem-lodestar
      #   url: 'https://github.com/sixthedge/totem-lodestar'
      #   branch: master
      #   options:
      #     out: "-o ../../api/totem-lodestar"
      #     glob: "./**/*.rb README.md"
      #     project: "-p totem-lodestar"
      #     url:     "--repository-url 'https://github.com/sixthedge/totem-lodestar'"

