text:
  title: Totem docs
  logo:  false
modules:
  layout:
    full_width:
      enabled: true
      default: true

  versions:
    index_redirect: true

  side_bar:
    collapse:
      enabled:        true
      expanded_icon:  'fa fa-minus right'
      collapsed_icon: 'fa fa-plus right'

  table_of_contents:
    smooth_scroll:
      enabled: true
      speed:   300 # Milliseconds
    highlight: 
      enabled: true

  api:      
    repositories:
      - name: cellar
        url: 'https://github.com/sixthedge/cellar'
        branch: master
        options:
          out: '-o ../../api/cellar'
          glob: '"./src/**/*.rb" 
          "./src/**/*.coffee" 
          "./src/**/*.js" 
          "./src/**/*.scss" 
          "./src/**/*.yml" 
          "README.md"'
          except: '--except "./src/totem/api/vendor/**" 
          --except "./src/thinkspace/client/thinkspace-*/node_modules/**" 
          --except "./src/totem/client/totem-*/vendor/**"'
          project: '-p cellar'
          url: '--repository-url "https://github.com/sixthedge/cellar"'

      - name: totem-lodestar
        url: 'https://github.com/sixthedge/totem-lodestar'
        branch: master
        options:
          out: "-o ../../api/totem-lodestar"
          glob: '"./**/*.rb" "./**/*.rake" "./**/*.coffee" "./**/*.scss" "./**/*.js" "README.md"'
          except: '--except "./node_modules/**" --except "./lib/generators/totem/lodestar/install/templates/**"'

          project: "-p totem-lodestar"
          url:     "--repository-url 'https://github.com/sixthedge/totem-lodestar'"

